version: '3'

volumes:
  grafana-storage:
  openvas:

services:
  openvas:
    image: mikesplain/openvas
    restart: on-failure
    ports:
      - "7777:443"
    volumes:
      - "openvas:/data"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - openvas

  grafana:
    image: grafana/grafana-oss:9.4.3
    container_name: grafana
    restart: unless-stopped
    environment:
      - "GF_LOG_LEVEL=warn"
    ports:
      - "13000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-datasource:/etc/grafana/provisioning

  web_prometheus_client:
    build: prometheus_client
    ports:
      - "5000:5000"
  test_server:
    image: nginx
    ports:
      - "80:80"